services:
  nest-app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: mongoDB
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./mongo-data:/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file:
      - .env
