services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data
    env_file:
      - .mongo.env
